- name: Install iptables-persistent
  become: true
  apt:
    name: iptables-persistent
    state: present

- name: Setup (copy) rules for IPv4
  become: true
  template:
    src: "{{ inventory_hostname }}/ipv4.iptables-rules.j2"
    dest: /etc/iptables/rules.v4
    group: root
    owner: root
    mode: 0400
  notify:
    - Restart iptables-persistent

- name: Enable and start iptables-persistent
  become: true
  service:
    name: iptables.service
    enabled: true
    state: started